FROM node:18-alpine AS build

WORKDIR /app

COPY ./svelte-frontend/package.json ./
COPY ./svelte-frontend/package-lock.json ./

RUN npm install

COPY ./svelte-frontend ./

RUN npm run build

FROM nginx:latest

COPY --from=build /app/dist /usr/share/nginx/html
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
