name: API Test and Lint

on:
    push:
        paths:
            - 'python/api/**.py'
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements_dev.txt
              working-directory: ./python/api
            - name: Run ruff
              run: ruff check .
              working-directory: ./python/api
            - name: Run tests
              run: pytest tests/
              working-directory: ./python/api
