name: API Test and Lint

on:
    push:
        paths:
            - 'python/api/**.py'
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements_dev.txt
              working-directory: ./python/api
            - name: Run ruff
              run: ruff check .
              continue-on-error: true
              working-directory: ./python/api
            - name: Run tests
              run: pytest tests/
              working-directory: ./python/api
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action
              with:
                images: ghcr.io/${{ github.repository }}
            - name: Build and Push Image
              uses: docker/build-push-action@v4
              with:
                push: true
                context: ./python/api
                labels: ${{ steps.meta.outputs.labels }}
                tags: ${{ steps.meta.outputs.tags }}
