name: API Check and Build

on:
    push:
        paths:
            - 'python/api/**'
    workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements_dev.txt
              working-directory: ./python/api
            - name: Run ruff
              id: lint
              run: ruff check .
              continue-on-error: true
              working-directory: ./python/api
            - name: Run tests
              id: test
              run: pytest tests/
              working-directory: ./python/api
            - name: Comment on Commit
              uses: octokit/request-action@v2.x
              with:
                route: POST /repos/${{ github.repository }}/check-runs
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                INPUT_HEAD_SHA: ${{ github.sha }}
                INPUT_NAME: Python API Checks
                INPUT_STATUS: completed
                INPUT_CONCLUSION: failure
                INPUT_OUTPUT: |
                  title: Python API Checks Run
                  summary: ${{ join(steps.test.outputs.*, '\n') }}
              if: github.event_name == 'push' && steps.test.outcome == 'failure'
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: ghcr.io/${{ github.repository }}
            - name: Build and Push Image
              uses: docker/build-push-action@v4
              with:
                push: true
                context: ./python/api
                labels: ${{ steps.meta.outputs.labels }}
                tags: ${{ steps.meta.outputs.tags }}
